name: Setup Rust Builder
description: 'Prepare Rust Build Environment'

runs:
  using: "composite"
  steps:
    - name: Setup rust related environment variables
      shell: bash
      run: |
        # Disable full debug symbol generation to speed up CI build and keep memory down
        # "1" means line tables only, which is useful for panic tracebacks.
        # About `force-frame-pointers`, here's the discussion history: https://github.com/apache/opendal/issues/3756
        echo "RUSTFLAGS=-C force-frame-pointers=yes -C debuginfo=1" >> $GITHUB_ENV
        # Enable backtraces
        echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
        # Enable logging
        echo "RUST_LOG=opendal=trace" >> $GITHUB_ENV
        # Enable sparse index
        echo "CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse" >> $GITHUB_ENV
        # Make sure rust has been setup
        cargo version
