name: vsftpd
description: 'integration test for vsftpd'

runs:
  using: "composite"
  steps:
    - name: Setup vsftpd Server
      shell: bash
      working-directory: fixtures/ftp
      run: docker compose -f docker-compose-vsftpd.yml up -d --wait
