[log]
level = "Debug"
dir = "/var/log/replited/"

[[database]]
db = "/var/sqlite/test.db"

# each database has at least one replicate backend
[[database.replicate]]
name = "fs"
params.type = "Fs"
params.root = "/var/replited"

[[database.replicate]]
name = "S3"
params.type = "Fs"
params.endpoint_url = "http://127.0.0.1:9900"
params.bucket = "sqlite"
params.region = ""
params.root = ""
params.access_key_id = "minioadmin"
params.secret_access_key = "minioadmin"

# can add more than one database config
#[[database]]
#db = "/var/sqlite/test2.db"

#[[database.replicate]]