[log]
level = "Debug"
dir = "/var/log/litesync/"
to_stderr = true

[[database]]
path = "provider"

[[database.replicate]]
allow_insecure = true
params.type = "S3"
params.endpoint_url = "http://127.0.0.1:9900"
params.bucket = "replicate-bucket-1"
params.region = ""
params.security_token = ""
params.master_key = ""
params.root = ""
params.disable_credential_loader = false
params.enable_virtual_host_style = false
params.role_arn = ""
params.external_id = ""
params.access_key_id = "minioadmin"
params.secret_access_key = "minioadmin"

[[database.replicate]]
allow_insecure = true
params.type = "S3"
params.endpoint_url = "http://127.0.0.1:9900"
params.bucket = "replicate-bucket-2"
params.region = ""
params.security_token = ""
params.master_key = ""
params.root = ""
params.disable_credential_loader = false
params.enable_virtual_host_style = false
params.role_arn = ""
params.external_id = ""
params.access_key_id = "minioadmin"
params.secret_access_key = "minioadmin"