[log]
level = "Debug"
dir = "/var/log/replited/"

[[database]]
db = "/var/sqlite/test.db"

# each database has at least one replicate backend, 
# each replication config in one db MUST has different name

# sample of gcs replicate config
[[database.replicate]]
name = "name of ccs"
params.type = "Gcs"
params.endpoint = "https://storage.googleapis.com"
params.bucket = "sqlite"
params.root = ""
params.credential = "xxx"

# sample of ftp replicate config
[[database.replicate]]
name = "name of ftp"
params.type = "Ftp"
params.endpoint = "https://storage.googleapis.com"
params.root = "/var/replited"
params.username = "username"
params.password = "password"

# sample of file system replicate config
[[database.replicate]]
name = "name of fs"
params.type = "Fs"
params.root = "/var/replited"

# sample of s3 replicate config
[[database.replicate]]
name = "name of s3"
params.type = "Fs"
params.endpoint = "http://127.0.0.1:9900"
params.bucket = "sqlite"
params.region = ""
params.root = ""
params.access_key_id = "minioadmin"
params.secret_access_key = "minioadmin"




# can add more than one database config
#[[database]]
#db = "/var/sqlite/test2.db"

#[[database.replicate]]
