name: Unit Test

on:
  schedule: # execute every 24 hours
    - cron: "* 0 * * *"
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v4
        with:
          # fetch depth set to 0 to make sure we have correct diff result.
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup

      - name: 'Run Unit tests'
        shell: bash
        run: |
          cargo test
